menu:
  logo: "/images/logo.svg"
  title: "Halo"
  align: "center" # left center
  icons: # align to right
  - name: "theme"
    default: "auto" # light dark auto
    responsive: "always"
  - name: "language"
    responsive: "md"
  - name: "link"
    responsive: "lg"
    icon: "github"
    blank: true
    translate: "github"
    target: "https://github.com/username/repo"
    section:
      exclude: ["docs"]
  - name: "link"
    responsive: "lg"
    icon: "user"        # lucide icons
    blank: false        # open with new tab, default false
    translate: "about"  # translation, nav_icon_label_xxx nav_icon_tip_xxx
    target: "/about/"   # http://example.com about
    section:
      exclude: ["docs"]
  - name: "button"
    responsive: "lg"
    icon: "user"        # lucide icons
    highlight: true     # 高亮显示
    blank: false        # open with new tab, default false
    translate: "about"  # translation, nav_icon_label_xxx nav_icon_tip_xxx
    target: "/about/"   # http://example.com about
    section:
      include: ["docs"]

toc:
  enable: true
  links:
  - disable: false
    icon: "messages-square"   # lucide icons
    blank: true               # open with new tab, default false
    translate: "forum"        # translation, toc_link_label_xxx
    target: "http://forum.example.com"

layout: # support 'full' 'wide' 'standard'
  width: "full"

example: http://github.com/example
